### ISSUE TITLE
Deprecate relayers and add manual bridging

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/gateway#197]
https://github.com/orgs/bobanetwork/projects/18

**Comment by sk-enya** [comment]
@InoMurko can you please share some more thoughts on, what does mean by manual bridging?

**Comment by InoMurko** [comment]
Is there something missing that isn't described in the URL in the initial comment???

**Comment by wsdt** [comment]
@InoMurko is that the general UX comparison with other L2s etc. that you were referring to earlier this week?

**Comment by InoMurko** [comment]
Yes

**Comment by wsdt** [comment]
Some initial notes on this for this: 
- Calendar reminder or similar, when withdrawal is ready (e.g. Arbitrum did that) -> means of reminding? E-Mail? Wallet communication tool? (e.g. EtherMail or similar projects?). To allow for pseudonymity we may need to make this optional.

- In general, KISS principle due to limited resources

- General pain point: No relayers in pain point, UI needs to be updated & users informed. 

- Since there will be no relayers, we should remove that message from the classic bridge (I assume we replace the classic bridge under the hood with a anchorage compatible bridge @InoMurko ?), related to https://github.com/orgs/bobanetwork/projects/18/views/1?pane=issue&itemId=28455933


- Create claim bridge or notification or similar on bridge page. Related to this: https://github.com/orgs/bobanetwork/projects/18/views/1?pane=issue&itemId=28647281


- Inform people on Gateway & other stakeholders that relayers are going away (inform the specifically about the consequences).

**Comment by wsdt** [comment]
Ino context on 28 Nov: 

Bedrock and withdrawals: https://community.optimism.io/docs/developers/bedrock/differences/#two-phase-withdrawals if there’s anything to futureproof.
Just re-check the withdrawal UX of Optimism. might have changed since I did the docs on the issue

**Comment by wsdt** [comment]
Own notes from 28 Nov: 
- After looking into OPs official bridge & third party bridges it looks like they mainly kept their existing user flow (except of obviously adding that 2nd step to the withdrawal process). 

Will discuss with Yoonhee, how to get that in as smoothly as possible.

**Comment by wsdt** [comment]
![image](https://github.com/bobanetwork/gateway/assets/28724551/1794ee24-6e87-4d9f-bab0-e72dbd9ceeef)

**Comment by wsdt** [comment]
Link to explanation: "https://blog.oplabs.co/two-step-withdrawals/"

**Comment by wsdt** [comment]
![image](https://github.com/bobanetwork/gateway/assets/28724551/add7b742-0679-4b9a-a7a5-99acf05cf275)

then switch to network L1

**Comment by wsdt** [comment]
![image](https://github.com/bobanetwork/gateway/assets/28724551/934af1f1-87bb-4e9b-9c9b-bae76ee779d8)

**Comment by wsdt** [comment]
rest should stay the same

**Comment by wsdt** [comment]
maybe from History back to modal screen to confirm 2nd transaction or similar

**Comment by wsdt** [comment]
Tested flow on testnet, initiate tx was just 5 min (but since they reduced the 7 day window to instantly claiming, we could assume the first flow (up to 1 hour according to docs) was shortened down to 5 min too.

**Comment by wsdt** [comment]
Mockups: 
https://www.figma.com/file/MKj9nofAYq0GOTziHaeWRL/Boba-Gateway-2.5?type=design&node-id=0%3A1&mode=design&t=xDvkIyqsSFVzfSup-1

**Comment by sk-enya** [comment]
Feature has been implemented and successfully release to production!
