### ISSUE TITLE
Light Bridge Connection Flow

### ISSUE THREAD

**Issue by jemeza** [bobanetwork/gateway#276]
How should the user go about switching between networks in the light bridge? Given that the user can connect from any L1 or L2 to any other L1 or L2 we cannot use the same process that is used for the classic bridge.

**Comment by souradeep-das** [comment]
It will be interesting to look into third-party cross-chain services and their swap pages for motivation. For instance, an example is here: https://app.symbiosis.finance/swap

**Comment by thenursegreg42069** [comment]
@jemeza can you describe more the issue? Why can't the same connection flow be used?

**Comment by wsdt** [comment]
The issue was (and still is from a technical design point of view) that we have a tightly coupled network logic on the Gateway (technical debt). 

Basically when switching from Boba ETH to Boba BNB we also simultaneously switch to Goerli (L1) and BNB (L1) in the background and then just change the layer. 

Instead of common practice that we basically have these networks independently configured and can switch to any chain as we wish. 

This created a lot of hassle adding Optimism/Arbitrum as well. 

A while ago I created an issue for that and tried to fix it, until I realized that this is potentially a huge undertaking and deprioritized it: 
https://github.com/bobanetwork/gateway/issues/65

For the light bridge delivery we have no blockers here, the issue has been solved (but it's not clean or beautiful so we might wanna look into the issue above when we have spare resources or plan to add many more networks etc.)

**Comment by thenursegreg42069** [comment]
That’s helpful context, thank you @wsdt 

imo if it’s not a hard blocker, isn’t a net negative UX, and simply a matter of “it could be a little smoother” let’s ship it and we can iterate on the design over time as it fits in the priority queue.

**Comment by jemeza** [comment]
The biggest issue I see is that the user is faced with two pop ups, one from metamask and another from the gateway. Which may be confusing but I think most users will be able to figure it out.

Below is an example: 

https://github.com/bobanetwork/gateway/assets/57341979/58d1bbac-d1ec-46f0-9333-936343d5d449

**Comment by souradeep-das** [comment]
Re - the two popups, can we send the network change prompt to metamask after the click on "switch to" button. seems worth solving

**Comment by thenursegreg42069** [comment]
> The biggest issue I see is that the user is faced with two pop ups, one from metamask and another from the gateway. Which may be confusing but I think most users will be able to figure it out.
> 
> Below is an example:
> 
>  potentialIssues.mp4

this doesn't seem like a major issue. More like a minor quality of life thing we can fix later. I know many live in production bridges that work this exact way right now.

**Comment by wsdt** [comment]
yes also think it is neglectable and a consequence of technical debt for now. 
Nonetheless, I added the switch network modal now as well so that it shouldn't show up.

**Comment by wsdt** [comment]
resolved in prior PRs.
