### ISSUE TITLE
Light Bridge Front End

### ISSUE THREAD

**Issue by thenursegreg42069** [bobanetwork/gateway#58]
The Light Bridge front end needs to be designed and integrated into the existing Gateway UI. 

1. Remove Fast Bridge from the Gateway UI. Replace with Light Bridge.
2. Initial chains supported will be Ethereum, Boba ETH L2, Optimism, Arbitrum

**Comment by wsdt** [comment]
Tagging #30

**Comment by wsdt** [comment]
Deprecation of fast bridge (according to mockups): 
https://github.com/bobanetwork/gateway/issues/87

Would do the change of removing fast bridge from tabs/history once light bridge is live on mainnet. 

---

@sk-enya only thing left in this regard is the integration of Optimism/Arbitrum, otherwise mockup feedback should be implemented. 

Do we already have plans on how we integrate those two networks? 
Can imagine we might run into some issues if we don't architect it properly since optimism/arbitrum will probably only be available for light bridge and all other contracts & bridges won't.

**Comment by sk-enya** [comment]
@wsdt absolutely, we haven't think about this yet so definitely we need architect the code in such way that we can support the Optimism and Arbitrum. open for thoughts and suggestions.

Just to confirm @wsdt you mean to say we will handle this once production deployment done for light bridge or have to release both together.

**Comment by wsdt** [comment]
@thenursegreg42069 do we only want to allow onboarding from Arbitrum / Optimism to Boba via Light bridge or also provide liquidity & support for Arbitrum/Optimism to exit Boba?

**Comment by wsdt** [comment]
Closing this issue in favor of: 
- https://github.com/bobanetwork/gateway/issues/92
- https://github.com/bobanetwork/gateway/issues/87

Feel free to reopen if you think this is a mistake.
